package store

import (
	"crypto/sha256"
	"encoding/hex"
	"strconv"
	"strings"
	"time"

	"smalux-speedtest/internal/model"
)

const (
	// These messages are generated by the server scheduler, not by a remote
	// Client. They are safe, stable categories and therefore remain more useful
	// than the generic client failure bucket.
	taskDetailAllClientsFailed         = "all clients failed"
	taskDetailSomeClientsIncomplete    = "some clients did not complete"
	taskDetailServerRestarted          = "server restarted before task completed"
	taskDetailTaskExpired              = "task expired after 10 minutes"
	taskDetailCanceledByAdministrator  = "canceled by administrator"
	taskDetailClientTokenRevoked       = "client token revoked"
	taskDetailClientDisconnected       = "client disconnected"
	taskDetailClientConnectionReplaced = "client connection replaced"
	taskDetailFinished                 = "finished"
)

// normalizePersistedProxyID accepts only IDs generated by model.NewID. A
// deterministic 128-bit SHA-256 prefix is used for legacy/direct callers so
// uniqueness and result grouping remain stable without storing attacker text.
func normalizePersistedProxyID(value string) string {
	value = strings.ToLower(strings.TrimSpace(value))
	if len(value) == 32 {
		if _, err := hex.DecodeString(value); err == nil {
			return value
		}
	}
	digest := sha256.Sum256([]byte(value))
	return hex.EncodeToString(digest[:16])
}

// normalizePersistedTaskDetail is the last write boundary for task and target
// error columns. Empty detail stays empty; known server-generated categories
// remain specific, while every other caller-controlled string is folded by the
// model's fixed client-failure classifier.
func normalizePersistedTaskDetail(value string) string {
	value = strings.TrimSpace(value)
	if value == "" {
		return ""
	}
	switch value {
	case model.TaskFailureTimeout, model.TaskFailureCanceled, model.TaskFailureClient,
		taskDetailAllClientsFailed, taskDetailSomeClientsIncomplete, taskDetailServerRestarted,
		taskDetailTaskExpired, taskDetailCanceledByAdministrator, taskDetailClientTokenRevoked,
		taskDetailClientDisconnected, taskDetailClientConnectionReplaced, taskDetailFinished:
		return value
	default:
		return model.NormalizeTaskFailure(value)
	}
}

// normalizePersistedTaskRead applies the same fixed status/detail boundary when a
// task is read. This protects API and Telegram responses if an old migration was
// interrupted or an operator restored a database whose rows were edited outside
// Store's write methods.
func normalizePersistedTaskRead(task Task) Task {
	if !validTaskStatus(task.Status) {
		task.Status = "failed"
	}
	task.Error = normalizePersistedTaskDetail(task.Error)
	task.CreatedAt = normalizePersistedTimestamp(task.CreatedAt)
	task.StartedAt = normalizePersistedTimestamp(task.StartedAt)
	task.FinishedAt = normalizePersistedTimestamp(task.FinishedAt)
	return task
}

// normalizePersistedTimestamp accepts only the UTC timestamp representation
// written by Store. Invalid legacy text is dropped so API, CSV, image, and Bot
// output cannot echo arbitrary values from a restored or manually edited row.
func normalizePersistedTimestamp(value string) string {
	value = strings.TrimSpace(value)
	if value == "" {
		return ""
	}
	parsed, err := time.Parse(time.RFC3339Nano, value)
	if err != nil {
		return ""
	}
	return parsed.UTC().Format(time.RFC3339Nano)
}

func validTaskStatus(status string) bool {
	switch status {
	case "queued", "running", "completed", "partial", "failed", "canceled":
		return true
	default:
		return false
	}
}

func validTargetStatus(status string) bool {
	switch status {
	case "queued", "running", "completed", "failed", "canceled":
		return true
	default:
		return false
	}
}

// normalizePersistedAddress accepts only the exact representation produced by
// model.MaskAddress. Any future caller that accidentally passes a raw or legacy
// partially masked address loses the entire host before SQL sees it.
func normalizePersistedAddress(value string) string {
	const prefix = "[redacted]:"
	if !strings.HasPrefix(value, prefix) {
		return "[redacted]"
	}
	portText := strings.TrimPrefix(value, prefix)
	port, err := strconv.ParseUint(portText, 10, 16)
	if err != nil || port == 0 {
		return "[redacted]"
	}
	return prefix + strconv.FormatUint(port, 10)
}

// normalizePersistedSpeedServerID converts arbitrary Client text into a short,
// deterministic identifier. Values already produced by Hub validation are retained
// so an idempotent result update keeps the same database conflict key.
func normalizePersistedSpeedServerID(value string) string {
	const prefix = "server-"
	if value == "server-unknown" {
		return value
	}
	if strings.HasPrefix(value, prefix) && len(value) == len(prefix)+16 {
		if _, err := hex.DecodeString(strings.TrimPrefix(value, prefix)); err == nil {
			return strings.ToLower(value)
		}
	}
	if value == "" {
		return "server-unknown"
	}
	digest := sha256.Sum256([]byte(value))
	return prefix + hex.EncodeToString(digest[:8])
}
